### ISSUE TITLE
[아이템 1] 생성자 대신 정적 팩터리 메서드를 고려하라

### ISSUE THREAD

**Issue by catsbi** [devbook-study/effectivejava#1]
- 아이템 번호 : 1
- 제목 : 생성자 대신 정적 팩터리 메서드를 고려하라
- 만료일 : 2021-12-05
- ETC:  해당 아이템에 대한 발표자료(링크 혹은 파일)등을 코멘트로 올려주세요.

**Comment by povia** [comment]
https://povia.tistory.com/75

**Comment by catsbi** [comment]
[아이템1](https://catsbi.oopy.io/d7f3a636-b613-453b-91c7-655d71fda2b1#b870b405-098e-4bea-9e90-96f151d03fe3)

**Comment by csbiy** [comment]
[item01.zip](https://github.com/devbook-study/effectivejava/files/7655636/item01.zip)

**Comment by tongnamuu** [comment]
https://www.notion.so/Item-1-c4cdd23e79234e9e9fa7884c7d4e44cc
