### ISSUE TITLE
[아이템 10] equals는 일반 규약을 지켜 재정의하라

### ISSUE THREAD

**Issue by catsbi** [devbook-study/effectivejava#10]
- 아이템 번호 :  10
- 제목 :   equals는 일반 규약을 지켜 재정의하라
- 만료일 : 2021-12-12

**Comment by catsbi** [comment]
[아이템 10](https://catsbi.oopy.io/313829e4-e869-48fe-9fb4-adcca06de1c5#6da72101-6de2-4088-b0c3-f3ddf0cd60fd)

**Comment by develiberta** [comment]
<a href src="https://www.notion.so/shleeverse/10-930e35c4cccc46598e194c855d4077c0">아이템 10

**Comment by develiberta** [comment]
<a href="https://www.notion.so/shleeverse/10-930e35c4cccc46598e194c855d4077c0">아이템 10

**Comment by csbiy** [comment]
[item10.md](https://github.com/devbook-study/effectivejava/files/7698482/item10.md)
