### ISSUE TITLE
[아이템 11] equals를 재정의하려거든 hashCode도 재정의하라 

### ISSUE THREAD

**Issue by catsbi** [devbook-study/effectivejava#11]
- 아이템 번호 :  11
- 제목 :  equals를 재정의하려거든 hashCode도 재정의하라 
- 만료일 : 2021-12-12

**Comment by catsbi** [comment]
[아이템 11](https://catsbi.oopy.io/313829e4-e869-48fe-9fb4-adcca06de1c5#8aa6d6b2-634a-439b-a531-7bc034a48b84)

**Comment by povia** [comment]
https://povia.tistory.com/87

**Comment by develiberta** [comment]
<a href="https://www.notion.so/shleeverse/11-8c8fc813a025491daf12d05536dd774e">아이템 11

**Comment by csbiy** [comment]
[item11.md](https://github.com/devbook-study/effectivejava/files/7698483/item11.md)
