### ISSUE TITLE
[아이템 12] toString을 항상 재정의하라

### ISSUE THREAD

**Issue by catsbi** [devbook-study/effectivejava#12]
- 아이템 번호 : 12
- 제목 : toString을 항상 재정의하라
- 만료일 : 2021-12-12

**Comment by catsbi** [comment]
[아이템 12](https://catsbi.oopy.io/313829e4-e869-48fe-9fb4-adcca06de1c5#3ef0485d-f6d4-40ce-ab17-52fb1f71f45e)

**Comment by povia** [comment]
https://povia.tistory.com/86

**Comment by develiberta** [comment]
<a href="https://www.notion.so/shleeverse/12-bba1d03161454c1aa67fc1b6ecd4dddd">아이템 12

**Comment by csbiy** [comment]
[item12.md](https://github.com/devbook-study/effectivejava/files/7698484/item12.md)
