### ISSUE TITLE
[아이템 13] clone 재정의는 주의해서 진행하라.

### ISSUE THREAD

**Issue by catsbi** [devbook-study/effectivejava#13]
- 아이템 번호 : 13
- 제목 :   clone 재정의는 주의해서 진행하라.
- 만료일 :  2021-12-12

**Comment by catsbi** [comment]
[아이템 13](https://catsbi.oopy.io/313829e4-e869-48fe-9fb4-adcca06de1c5#4b0ca40d-57be-432c-af1a-c8dc1e64839b)

**Comment by develiberta** [comment]
<a href="https://www.notion.so/shleeverse/13-5c804b4123ac4ddabd189c5e7e6b4989">아이템 13

**Comment by csbiy** [comment]
[item13.md](https://github.com/devbook-study/effectivejava/files/7698485/item13.md)
