### ISSUE TITLE
[아이템 14] Comparable을 구현할지 고려하라

### ISSUE THREAD

**Issue by catsbi** [devbook-study/effectivejava#14]
- 아이템 번호 :  14
- 제목 :   Comparable을 구현할지 고려하라
- 만료일 : 2021-12-12

**Comment by catsbi** [comment]
[아이템 14](https://catsbi.oopy.io/313829e4-e869-48fe-9fb4-adcca06de1c5#3374836c-6996-4565-ab1b-5829354603d5)

**Comment by povia** [comment]
https://povia.tistory.com/89

**Comment by develiberta** [comment]
<a href="https://www.notion.so/shleeverse/14-9a198c753b2f4b8b99c5ed6315152ae2">아이템 14
