### ISSUE TITLE
[아이템 15] 클래스와 멤버의 접근 권한을 최소화하라

### ISSUE THREAD

**Issue by catsbi** [devbook-study/effectivejava#15]
- 아이템 번호 :  15
- 제목 :  **클래스와 멤버의 접근 권한을 최소화하라**
- 만료일 : 2021-12-19

**Comment by catsbi** [comment]
[아이템 15](https://catsbi.oopy.io/1a9e0c15-464d-436d-806c-3713e6c4e224#f01faf6c-a014-4b95-86b2-527fd8c8e582)

**Comment by povia** [comment]
[Item 15](https://povia.tistory.com/90)

**Comment by JoyDaheeCha** [comment]
[아이템 15](https://joyful-class-maker.tistory.com/124)

**Comment by develiberta** [comment]
<a href="https://www.notion.so/shleeverse/15-7e06342f9d654fdbb62e7ef33b58b4c1">아이템 15

**Comment by csbiy** [comment]
https://devcs96.github.io/2021/12/17/2021-12-17-item15/#more
