### ISSUE TITLE
[아이템 16] public 클래스에서는 public 필드가 아닌 접근자 메서드를 사용하라.

### ISSUE THREAD

**Issue by catsbi** [devbook-study/effectivejava#16]
- 아이템 번호 :  16
- 제목 :   public 클래스에서는 public 필드가 아닌 접근자 메서드를 사용하라.
- 만료일 : 2021-12-19

**Comment by catsbi** [comment]
[아이템 16](https://catsbi.oopy.io/1a9e0c15-464d-436d-806c-3713e6c4e224#baaed900-5c32-4d88-a03b-f8b53cc9b154)

**Comment by povia** [comment]
[Item 16](https://povia.tistory.com/91)

**Comment by JoyDaheeCha** [comment]
[아이템 16](https://joyful-class-maker.tistory.com/125)

**Comment by develiberta** [comment]
<a href="https://shleeverse.notion.site/16-c43111b75a434c7882b6ea933cbec418">아이템 16

**Comment by csbiy** [comment]
https://devcs96.github.io/2021/12/17/2021-12-17-item16/#more
