### ISSUE TITLE
[아이템 17] 변경 가능성을 최소화하라.

### ISSUE THREAD

**Issue by catsbi** [devbook-study/effectivejava#17]
- 아이템 번호 :  17
- 제목 :  변경 가능성을 최소화하라.
- 만료일 : 2021-12-19

**Comment by catsbi** [comment]
[아이템 17](https://catsbi.oopy.io/1a9e0c15-464d-436d-806c-3713e6c4e224#e852877d-256f-49dc-961b-46fb45077ca2)

**Comment by povia** [comment]
[Item 17](https://povia.tistory.com/92)

**Comment by develiberta** [comment]
<a href="https://shleeverse.notion.site/17-d2227cf9dba74d769352d10be422d4e0">아이템 17

**Comment by csbiy** [comment]
https://devcs96.github.io/2021/12/17/2021-12-18-item17/

**Comment by JoyDaheeCha** [comment]
[아이템 17](https://joyful-class-maker.tistory.com/126)
