### ISSUE TITLE
[아이템 18] 상속보다는 컴포지션을 사용하라.

### ISSUE THREAD

**Issue by catsbi** [devbook-study/effectivejava#18]
- 아이템 번호 :  18
- 제목 : 상속보다는 컴포지션을 사용하라.
- 만료일 :  2021-12-19

**Comment by catsbi** [comment]
[아이템 18](https://catsbi.oopy.io/1a9e0c15-464d-436d-806c-3713e6c4e224#e0b6b64f-1b4b-4629-a244-a79d91c408ec)

**Comment by develiberta** [comment]
<a href="https://shleeverse.notion.site/18-9ba6bf73b6f14723aec333ece63d5abd">아이템 18

**Comment by povia** [comment]
[Item 18](https://povia.tistory.com/93)

**Comment by csbiy** [comment]
https://devcs96.github.io/2021/12/18/2021-12-18-item18/#more
