### ISSUE TITLE
[아이템 19] 상속을 고려해 설계하고 문서화하라. 그러지 않았다면 상속을 금지하라.

### ISSUE THREAD

**Issue by catsbi** [devbook-study/effectivejava#19]
- 아이템 번호 : 19
- 제목 :  상속을 고려해 설계하고 문서화하라. 그러지 않았다면 상속을 금지하라.
- 만료일 : 2021-12-19

**Comment by catsbi** [comment]
[아이템 19](https://catsbi.oopy.io/1a9e0c15-464d-436d-806c-3713e6c4e224#c089e5d8-5ae9-4c84-99b9-541f2711e664)

**Comment by develiberta** [comment]
<a href="https://shleeverse.notion.site/19-48f41a0138c14496a670d7ca5a2ae631">아이템 19

**Comment by csbiy** [comment]
https://devcs96.github.io/2021/12/19/2021-12-19-item19/

**Comment by povia** [comment]
[Item 19](https://povia.tistory.com/94)
