### ISSUE TITLE
[아이템 2] 생성자에 매개변수가 많다면 빌더를 고려하라

### ISSUE THREAD

**Issue by catsbi** [devbook-study/effectivejava#2]
- 아이템 번호 :  2
- 제목 :  생성자에 매개변수가 많다면 빌더를 고려하라
- 만료일 :  2021-12-05

**Comment by catsbi** [comment]
[아이템 2](https://catsbi.oopy.io/d7f3a636-b613-453b-91c7-655d71fda2b1#3e25c946-78cc-4911-82db-69f0cf4e82d2)

**Comment by povia** [comment]
https://povia.tistory.com/76

**Comment by csbiy** [comment]
[item02.zip](https://github.com/devbook-study/effectivejava/files/7655638/item02.zip)

**Comment by tongnamuu** [comment]
https://www.notion.so/Item-2-52da6db6c64a4f92abb1231825287bad
