### ISSUE TITLE
[아이템 20] 추상 클래스보다는 인터페이스를 우선하라

### ISSUE THREAD

**Issue by catsbi** [devbook-study/effectivejava#20]
- 아이템 번호 : 20
- 제목 :  추상 클래스보다는 인터페이스를 우선하라
- 만료일 :  2021-12-19

**Comment by catsbi** [comment]
[아이템 20](https://catsbi.oopy.io/1a9e0c15-464d-436d-806c-3713e6c4e224#23a7ee64-f60e-465b-8061-ff60c6145c1c)

**Comment by povia** [comment]
[Item 20](https://povia.tistory.com/95)

**Comment by develiberta** [comment]
<a href="https://shleeverse.notion.site/20-587c2081f23e4103a5636d04fad52be8">아이템 20
