### ISSUE TITLE
[아이템 21] 인터페이스는 구현하는 쪽을 생각해 설계하라

### ISSUE THREAD

**Issue by catsbi** [devbook-study/effectivejava#22]
- 아이템 번호 :  21
- 제목 :  인터페이스는 구현하는 쪽을 생각해 설계하라
- 만료일 : 2021-12-26

**Comment by catsbi** [comment]
[아이템 21](https://catsbi.oopy.io/1a9e0c15-464d-436d-806c-3713e6c4e224#6580b404-86e1-4e72-8f51-ef1adb4f92d7)

**Comment by povia** [comment]
[아이템 21](https://povia.tistory.com/97)

**Comment by csbiy** [comment]
https://devcs96.github.io/2021/12/22/2021-12-22-item21/#more

**Comment by JoyDaheeCha** [comment]
https://joyful-class-maker.tistory.com/131

**Comment by develiberta** [comment]
<a href="https://shleeverse.notion.site/21-e126b41fc26948e69189ae85c5e23d34">아이템 21
