### ISSUE TITLE
[아이템 22] 인터페이스는 타입을 정의하는 용도로만 사용하라

### ISSUE THREAD

**Issue by catsbi** [devbook-study/effectivejava#23]
- 아이템 번호 : 22
- 제목 :  인터페이스는 타입을 정의하는 용도로만 사용하라
- 만료일 : 2021-12-26

**Comment by catsbi** [comment]
[아이템 22](https://catsbi.oopy.io/1a9e0c15-464d-436d-806c-3713e6c4e224#2fcf0dbb-7f8d-4d2c-afc4-3629e0c3c573)

**Comment by povia** [comment]
[아이템 22](https://povia.tistory.com/98)

**Comment by csbiy** [comment]
https://devcs96.github.io/2021/12/22/2021-12-22-item22/

**Comment by JoyDaheeCha** [comment]
https://joyful-class-maker.tistory.com/131

**Comment by develiberta** [comment]
<a href="https://shleeverse.notion.site/22-88dc4eae610641e7b81bab7c424b95b1">아이템 22

**Comment by tongnamuu** [comment]
https://www.notion.so/Item-22-d6a08ffe39334a3da2334fde023c64c7
