### ISSUE TITLE
[아이템 23]  태그 달린 클래스보다는 클래스 계층구조를 활용하라

### ISSUE THREAD

**Issue by catsbi** [devbook-study/effectivejava#24]
- 아이템 번호 :  23
- 제목 :  태그 달린 클래스보다는 클래스 계층구조를 활용하라
- 만료일 : 2021-12-26

**Comment by catsbi** [comment]
[아이템 23](https://catsbi.oopy.io/1a9e0c15-464d-436d-806c-3713e6c4e224#3ed5b3ad-69bc-43d7-ae66-302926e48bbf)

**Comment by povia** [comment]
[아이템 23](https://povia.tistory.com/99)

**Comment by csbiy** [comment]
https://devcs96.github.io/2021/12/25/2021-12-25-item23/

**Comment by JoyDaheeCha** [comment]
https://joyful-class-maker.tistory.com/131

**Comment by tongnamuu** [comment]
https://www.notion.so/Item-23-0a661146e8c4435b96331d0650b4b1aa

**Comment by develiberta** [comment]
<a href="https://shleeverse.notion.site/23-a75d62c6c47e456db1b70a3fddaf1d01">아이템 23
