### ISSUE TITLE
[아이템 24] 멤버 클래스는 되도록 static으로 만들어라

### ISSUE THREAD

**Issue by catsbi** [devbook-study/effectivejava#25]
- 아이템 번호 :  24
- 제목 :  멤버 클래스는 되도록 static으로 만들어라
- 만료일 : 2021-12-26

**Comment by catsbi** [comment]
[아이템 24](https://catsbi.oopy.io/1a9e0c15-464d-436d-806c-3713e6c4e224#7b1c74ee-8855-45f9-a69e-6ec303924e2c)

**Comment by csbiy** [comment]
https://devcs96.github.io/2021/12/25/2021-12-25-item24/

**Comment by povia** [comment]
[아이템 24](https://povia.tistory.com/100)

**Comment by JoyDaheeCha** [comment]
https://joyful-class-maker.tistory.com/131

**Comment by develiberta** [comment]
<a href="https://shleeverse.notion.site/24-5f378781d68f4144bac47105c6b3a6e8">아이템 24
