### ISSUE TITLE
[아이템 25] 톱레벨 클래스는 한 파일에 하나만 담으라

### ISSUE THREAD

**Issue by catsbi** [devbook-study/effectivejava#26]
- 아이템 번호 : 25
- 제목 :  톱레벨 클래스는 한 파일에 하나만 담으라
- 만료일 : 2021-12-26

**Comment by catsbi** [comment]
[아이템 25](https://catsbi.oopy.io/1a9e0c15-464d-436d-806c-3713e6c4e224#9e9d4018-7c29-4fc7-bf28-95bb80d1d592)

**Comment by povia** [comment]
[아이템 25](https://povia.tistory.com/101)

**Comment by csbiy** [comment]
https://devcs96.github.io/2021/12/26/2021-12-26-item25/

**Comment by JoyDaheeCha** [comment]
https://joyful-class-maker.tistory.com/131

**Comment by develiberta** [comment]
<a href="https://shleeverse.notion.site/25-04538ad65528479aa17a6a7494461edf">아이템 25

**Comment by tongnamuu** [comment]
https://www.notion.so/Item-25-08f4609e39be412e9fef8ef7e210cdbd
