### ISSUE TITLE
[아이템 26] 로 타입은 사용하지 말라

### ISSUE THREAD

**Issue by catsbi** [devbook-study/effectivejava#27]
- 아이템 번호 : 26
- 제목 :  로 타입은 사용하지 말라
- 만료일 : 2022-01-02

**Comment by catsbi** [comment]
[아이템 26](https://catsbi.oopy.io/83635cfe-1cab-43f2-a943-56a9efd83fb2#3af5139e-bfd9-4acd-a884-0f7a4e5a7d8d)

**Comment by JoyDaheeCha** [comment]
아이템 26: https://joyful-class-maker.tistory.com/134

**Comment by csbiy** [comment]
https://devcs96.github.io/2021/12/28/2021-12-28-item26/#more

**Comment by povia** [comment]
[아이템 26](https://povia.tistory.com/102)

**Comment by tongnamuu** [comment]
https://www.notion.so/Item-26-7a18b327975048d29fb49c2bb8c83e13
