### ISSUE TITLE
[아이템 27] 비검사 경고를 제거하라.

### ISSUE THREAD

**Issue by catsbi** [devbook-study/effectivejava#28]
- 아이템 번호 :  27
- 제목 :   비검사 경고를 제거하라.
- 만료일 : 2022-01-02

**Comment by catsbi** [comment]
[아이템 27](https://catsbi.oopy.io/83635cfe-1cab-43f2-a943-56a9efd83fb2#ffd21a58-1265-4fa6-ad0b-6c20e6bb9820)

**Comment by JoyDaheeCha** [comment]
아이템 27: https://joyful-class-maker.tistory.com/135

**Comment by csbiy** [comment]
https://devcs96.github.io/2021/12/28/2021-12-28-item27/#more

**Comment by povia** [comment]
[아이템 27](https://povia.tistory.com/103)

**Comment by tongnamuu** [comment]
https://www.notion.so/Item-27-66fc692cb2d74b6697ce5c9f68c48ce5
