### ISSUE TITLE
[아이템 28] 배열보다는 리스트를 사용하라.

### ISSUE THREAD

**Issue by catsbi** [devbook-study/effectivejava#29]
- 아이템 번호 : 28
- 제목 : 배열보다는 리스트를 사용하라.
- 만료일 :2022-01-02

**Comment by catsbi** [comment]
[아이템 28](https://catsbi.oopy.io/83635cfe-1cab-43f2-a943-56a9efd83fb2#3fb74220-f29e-402d-b5cb-8269f264cb1d)

**Comment by JoyDaheeCha** [comment]
아이템 28: https://joyful-class-maker.tistory.com/136

**Comment by csbiy** [comment]
https://devcs96.github.io/2021/12/29/2021-12-29-item28/#more

**Comment by povia** [comment]
[아이템 28](https://povia.tistory.com/104)

**Comment by tongnamuu** [comment]
https://www.notion.so/Item-28-9dbaeab6010c423f958541bf049d9108
