### ISSUE TITLE
[아이템 3] private 생성자나 열거 타입으로 싱글턴임을 보증하라

### ISSUE THREAD

**Issue by catsbi** [devbook-study/effectivejava#3]
- 아이템 번호 :  3
- 제목 :  private 생성자나 열거 타입으로 싱글턴임을 보증하라
- 만료일 : 2021-12-05

**Comment by catsbi** [comment]
[아이템 3](https://catsbi.oopy.io/d7f3a636-b613-453b-91c7-655d71fda2b1#d5298a23-49aa-47d4-8ad4-e6fe5521fb5c)

**Comment by povia** [comment]
https://povia.tistory.com/78

**Comment by csbiy** [comment]
[item03.zip](https://github.com/devbook-study/effectivejava/files/7655639/item03.zip)

**Comment by tongnamuu** [comment]
https://www.notion.so/Item-3-private-11a6a4bf03374afcbf93a1b6136e9eb9
