### ISSUE TITLE
[아이템 29] 이왕이면 제네릭 타입으로 만들라

### ISSUE THREAD

**Issue by catsbi** [devbook-study/effectivejava#30]
- 아이템 번호 : 29
- 제목 : 이왕이면 제네릭 타입으로 만들라
- 만료일 : 2022-01-02

**Comment by catsbi** [comment]
[아이템 29](https://catsbi.oopy.io/83635cfe-1cab-43f2-a943-56a9efd83fb2#138a7431-32b1-4dc6-a6ea-ddc7c3b57776)

**Comment by csbiy** [comment]
https://devcs96.github.io/2021/12/30/2021-12-30-Item29/#more

**Comment by povia** [comment]
[아이템 29](https://povia.tistory.com/105)

**Comment by tongnamuu** [comment]
https://www.notion.so/Item-29-510db809a7f044f4928d72a5ecac3571
