### ISSUE TITLE
[아이템 30] 이왕이면 제네릭 메서드로 만들라

### ISSUE THREAD

**Issue by catsbi** [devbook-study/effectivejava#31]
- 아이템 번호 : 30
- 제목 : 이왕이면 제네릭 메서드로 만들라
- 만료일 :2022-01-02

**Comment by csbiy** [comment]
https://devcs96.github.io/2022/01/01/2022-01-01-Item30/#more

**Comment by povia** [comment]
[아이템 30](https://povia.tistory.com/106)

**Comment by catsbi** [comment]
[아이템 30](https://catsbi.oopy.io/83635cfe-1cab-43f2-a943-56a9efd83fb2#87498c31-f1c4-4358-908d-7ddf5c14f2cd)
