### ISSUE TITLE
[아이템 31] 한정적 와일드카드를 사용해 API 유연성을 높이라

### ISSUE THREAD

**Issue by catsbi** [devbook-study/effectivejava#32]
- 아이템 번호 : 31
- 제목 : 31. 한정적 와일드카드를 사용해 API 유연성을 높이라
- 만료일 : 2022-01-09

**Comment by csbiy** [comment]
https://devcs96.github.io/2022/01/03/2022-01-03-Item31/#more

**Comment by JoyDaheeCha** [comment]
아이템 31: https://joyful-class-maker.tistory.com/140

**Comment by catsbi** [comment]
[아이템31](https://catsbi.oopy.io/83635cfe-1cab-43f2-a943-56a9efd83fb2#c0063068-9f63-402c-a511-ffc90aa98619)

**Comment by povia** [comment]
[노션](https://pumped-hell-0a1.notion.site/Item-31-Use-bounded-wildcards-to-increase-API-flexibility-b3e75aa2048b405ea3d3fc1e5187b0e4)

**Comment by develiberta** [comment]
아이템 31<a href="https://shleeverse.notion.site/31-8fba3c10b744465a8210036c27b65aaa">

**Comment by develiberta** [comment]
<a href="https://shleeverse.notion.site/31-8fba3c10b744465a8210036c27b65aaa">아이템 31
