### ISSUE TITLE
[아이템 32] 제네릭과 가변인수를 함께 쓸 때는 신중하라

### ISSUE THREAD

**Issue by catsbi** [devbook-study/effectivejava#33]
- 아이템 번호 : 32
- 제목 :  제네릭과 가변인수를 함께 쓸 때는 신중하라
- 만료일 : 2022-01-09

**Comment by csbiy** [comment]
https://devcs96.github.io/2022/01/04/2022-01-04-Item32/#more

**Comment by JoyDaheeCha** [comment]
아이템 32: https://joyful-class-maker.tistory.com/140

**Comment by catsbi** [comment]
[아이템32](https://catsbi.oopy.io/83635cfe-1cab-43f2-a943-56a9efd83fb2#7c48475a-84f0-421a-9d01-baaab53bffb1)

**Comment by povia** [comment]
[노션](https://pumped-hell-0a1.notion.site/Item-32-Combine-generics-and-varargs-judiciously-d1cc65d3e35b4f6c99e7283f6c956db9)

**Comment by develiberta** [comment]
<a href="https://shleeverse.notion.site/32-717b453cc5bc438c8aa797468a31cb05">아이템 32
