### ISSUE TITLE
[아이템 33] 타입 안전 이종 컨테이너를 고려하라. 

### ISSUE THREAD

**Issue by catsbi** [devbook-study/effectivejava#34]
- 아이템 번호 : 33
- 제목 :  타입 안전 이종 컨테이너를 고려하라. 
- 만료일 : 2022-01-09

**Comment by csbiy** [comment]
https://devcs96.github.io/2022/01/05/2022-01-05-Item33/#more

**Comment by catsbi** [comment]
[아이템33](https://catsbi.oopy.io/83635cfe-1cab-43f2-a943-56a9efd83fb2#30bc5f35-f5a5-41d4-852f-647f31cd0bf0)

**Comment by povia** [comment]
[노션](https://pumped-hell-0a1.notion.site/Item-33-Consider-typesafe-heterogeneous-containers-cdc42e0cd23346548b16437677414a8e)

**Comment by develiberta** [comment]
<a href="https://shleeverse.notion.site/33-3f3518c573714e19980d511616e79781">아이템 33
