### ISSUE TITLE
[아이템 34] int 상수 대신 열거 타입을 사용하라

### ISSUE THREAD

**Issue by catsbi** [devbook-study/effectivejava#35]
- 아이템 번호 : 34
- 제목 :  int 상수 대신 열거 타입을 사용하라
- 만료일 : 2022-01-09

**Comment by csbiy** [comment]
https://devcs96.github.io/2022/01/06/2022-01-06-Item34/#more

**Comment by catsbi** [comment]
[아이템34](https://catsbi.oopy.io/4678b976-bd7e-4353-b4f0-04c06f66df03#43d0f4e7-812b-4639-9f8b-3e6b94682546)

**Comment by povia** [comment]
[노션](https://pumped-hell-0a1.notion.site/Item-34-Use-enums-instead-of-int-constants-b7dc6e3acf0d420f95c9c18236a07556)

**Comment by develiberta** [comment]
<a href="https://shleeverse.notion.site/34-822cb750a28c4a46965bb36a23fb464f">아이템 34

**Comment by JoyDaheeCha** [comment]
아이템 34: https://joyful-class-maker.tistory.com/140

**Comment by tongnamuu** [comment]
https://www.notion.so/Item-34-int-fd88beb5ee2846c5b392526282a24904
