### ISSUE TITLE
[아이템 35] int 상수 대신 열거 타입을 사용하라

### ISSUE THREAD

**Issue by catsbi** [devbook-study/effectivejava#36]
- 아이템 번호 : 35
- 제목 :  int 상수 대신 열거 타입을 사용하라
- 만료일 : 2022-01-09

**Comment by csbiy** [comment]
https://devcs96.github.io/2022/01/08/2022-01-08-Item35/#more

**Comment by catsbi** [comment]
[아이템 35](https://catsbi.oopy.io/4678b976-bd7e-4353-b4f0-04c06f66df03#deebeb07-b15a-4cdb-a822-6a1424f34d31)

**Comment by JoyDaheeCha** [comment]
아이템 35: https://joyful-class-maker.tistory.com/140

**Comment by povia** [comment]
[노션](https://pumped-hell-0a1.notion.site/Item-35-Use-instance-fields-instead-of-ordinals-008b22ea8d6e4971939d3df8710ef1b9)

**Comment by develiberta** [comment]
<a href="https://shleeverse.notion.site/35-ceb0d2894e2e4407a4ac34272290ae0b">아이템 35

**Comment by tongnamuu** [comment]
https://www.notion.so/Item-35-ordinal-35b88e259d304f4998ca7d5222c100e3
