### ISSUE TITLE
[아이템 36]  비트 필드 대신 EnumSet을 사용하라.

### ISSUE THREAD

**Issue by catsbi** [devbook-study/effectivejava#37]
- 아이템 번호 : 36
- 제목 :   비트 필드 대신 EnumSet을 사용하라.
- 만료일 : 2022-01-16

**Comment by catsbi** [comment]
[아이템 36](https://catsbi.oopy.io/4678b976-bd7e-4353-b4f0-04c06f66df03#de76083f-8770-49ab-b639-3b1a7e59dc2c)

**Comment by csbiy** [comment]
https://devcs96.github.io/2022/01/11/2022-01-11-Item36/#more

**Comment by develiberta** [comment]
<a href="https://shleeverse.notion.site/36-6c5ea7b160614cf8b54eefbd7e14a314">아이템 36

**Comment by povia** [comment]
[아이템 36](https://pumped-hell-0a1.notion.site/Item-36-Use-EnumSet-instead-of-bit-fields-c5392e9ca27740bc935a6638280932cf)

**Comment by tongnamuu** [comment]
https://www.notion.so/Item-36-EnumSet-efa59f43363e42ce896102df049fbe4a
