### ISSUE TITLE
[아이템 37] ordinal 인덱싱 대신 EnumMap을 사용하라

### ISSUE THREAD

**Issue by catsbi** [devbook-study/effectivejava#38]
- 아이템 번호 : 37
- 제목 : ordinal 인덱싱 대신 EnumMap을 사용하라
- 만료일 :2022-01-16

**Comment by catsbi** [comment]
[아이템 37](https://catsbi.oopy.io/4678b976-bd7e-4353-b4f0-04c06f66df03#abaa6bdd-8ac1-4122-99e7-72ba2a483236)

**Comment by csbiy** [comment]
https://devcs96.github.io/2022/01/11/2022-01-11-Item37/#more

**Comment by develiberta** [comment]
<a href="https://shleeverse.notion.site/37-91e021f9000246cbbb461209a48065dc">아이템 37

**Comment by povia** [comment]
[아이템 37](https://pumped-hell-0a1.notion.site/Item-37-Use-EnumMap-instead-of-ordinal-indexing-b75de694c9914ff5b154bc356fa3619a)

**Comment by tongnamuu** [comment]
https://www.notion.so/Item-37-ordinal-EnumMap-7df50e9a4c3348aa93f77c25cef662e9
