### ISSUE TITLE
[아이템 38] 확장할 수 있는 열거 타입이 필요하면 인터페이스를 사용하라.

### ISSUE THREAD

**Issue by catsbi** [devbook-study/effectivejava#39]
- 아이템 번호 : 38
- 제목 : 확장할 수 있는 열거 타입이 필요하면 인터페이스를 사용하라.
- 만료일 :2022-01-16

**Comment by csbiy** [comment]
https://devcs96.github.io/2022/01/12/2022-01-12-Item38/#more

**Comment by develiberta** [comment]
<a href="https://shleeverse.notion.site/38-401d732c1f134560b0cab0dff4118ba3">아이템 38

**Comment by catsbi** [comment]
[아이템 38](https://catsbi.oopy.io/4678b976-bd7e-4353-b4f0-04c06f66df03#bbe733b5-ec53-46c2-bffe-cd2c05bae69e)

**Comment by povia** [comment]
[아이템 38](https://pumped-hell-0a1.notion.site/Item-38-Emulate-extensible-enums-with-interfaces-f0f7bd44c10441b1a387cfe9873695ad)

**Comment by tongnamuu** [comment]
https://www.notion.so/Item-38-7a1a37c69308499ca13a80dcd394fb26
