### ISSUE TITLE
[아이템 4] 인스턴스화를 막으려거든 private 생성자를 사용하라.

### ISSUE THREAD

**Issue by catsbi** [devbook-study/effectivejava#4]
- 아이템 번호 :  4
- 제목 : 인스턴스화를 막으려거든 private 생성자를 사용하라
- 만료일 : 2021-12-05

**Comment by povia** [comment]
https://povia.tistory.com/79

**Comment by catsbi** [comment]
[아이템 4](https://catsbi.oopy.io/d7f3a636-b613-453b-91c7-655d71fda2b1#dd6b1691-92e0-4b0f-bb2e-e9d15fc51d05)

**Comment by csbiy** [comment]
[item04.zip](https://github.com/devbook-study/effectivejava/files/7655641/item04.zip)

**Comment by tongnamuu** [comment]
https://www.notion.so/Item-4-private-c7e835029e6248e088f3de972151d347
