### ISSUE TITLE
[아이템 39] 명명 패턴보다 애너테이션을 사용하라.

### ISSUE THREAD

**Issue by catsbi** [devbook-study/effectivejava#40]
- 아이템 번호 : 39
- 제목 : 명명 패턴보다 애너테이션을 사용하라.
- 만료일 : 2022-01-16

**Comment by csbiy** [comment]
https://devcs96.github.io/2022/01/13/2022-01-13-Item39/#more

**Comment by develiberta** [comment]
<a href="https://shleeverse.notion.site/39-1484a53f3a3f4318bdabda3d686417aa">아이템 39

**Comment by catsbi** [comment]
[아이템 39](https://catsbi.oopy.io/4678b976-bd7e-4353-b4f0-04c06f66df03#289e5b92-226d-4b06-b252-c2228f598ecc)

**Comment by povia** [comment]
[아이템 39](https://pumped-hell-0a1.notion.site/Item-39-Prefer-annotations-to-naming-patterns-be3598bdca704aae9efa0069cb505393)
