### ISSUE TITLE
[아이템 40] @Override 애너테이션을 일관되게 사용하라

### ISSUE THREAD

**Issue by catsbi** [devbook-study/effectivejava#41]
- 아이템 번호 :  40
- 제목 :  @Override 애너테이션을 일관되게 사용하라
- 만료일 : 2022-01-16

**Comment by csbiy** [comment]
https://devcs96.github.io/2022/01/14/2022-01-15-Item40/#more

**Comment by develiberta** [comment]
<a href="https://shleeverse.notion.site/40-adb7f7896fb643438e502fd148889ff2">아이템 40

**Comment by catsbi** [comment]
[아이템 40](https://catsbi.oopy.io/4678b976-bd7e-4353-b4f0-04c06f66df03#813f7158-9867-4315-9f66-b54dc0288f80)

**Comment by povia** [comment]
[아이템 40](https://pumped-hell-0a1.notion.site/Item-40-Consistently-use-the-Override-annotation-8f0bbc8c1403403dbdb3a5a19c500a7c)

**Comment by tongnamuu** [comment]
https://www.notion.so/Item-40-Override-e8f9549fb2c54cf0b5b978a904c39168
