### ISSUE TITLE
[아이템 41] 정의하려는 것이 타입이라면 마커 인터페이스를 사용하라.

### ISSUE THREAD

**Issue by catsbi** [devbook-study/effectivejava#42]
- 아이템 번호 : 41
- 제목 :  정의하려는 것이 타입이라면 마커 인터페이스를 사용하라.
- 만료일 : 2022-01-23

**Comment by catsbi** [comment]
[아이템 41](https://catsbi.oopy.io/4678b976-bd7e-4353-b4f0-04c06f66df03#2b143d40-b3ee-49da-abc9-9a8dcb82f8c0)

**Comment by csbiy** [comment]
https://devcs96.github.io/2022/01/17/2022-01-17-Item41/#more

**Comment by JoyDaheeCha** [comment]
https://joyful-class-maker.tistory.com/149

**Comment by develiberta** [comment]
<a href="https://shleeverse.notion.site/41-e0564093fc9d49c4a23871f6341e56d8">아이템 41

**Comment by povia** [comment]
[아이템 41](https://pumped-hell-0a1.notion.site/Item-41-Use-marker-interfaces-to-define-types-0888dd18a4ed4995be1e723afad623d5)
