### ISSUE TITLE
[아이템 42] 익명 클래스보다는 람다를 사용하라.

### ISSUE THREAD

**Issue by catsbi** [devbook-study/effectivejava#43]
- 아이템 번호 : 42
- 제목 : 익명 클래스보다는 람다를 사용하라.
- 만료일 : 2022-01-23

**Comment by catsbi** [comment]
[아이템 42](https://catsbi.oopy.io/5861b4b5-60fa-4a6e-aadf-5caeafe68b1e#3a78ce65-88bb-4cc9-a227-e39b7ee18af1)

**Comment by csbiy** [comment]
https://devcs96.github.io/2022/01/18/2022-01-18-Item42/#more

**Comment by JoyDaheeCha** [comment]
https://joyful-class-maker.tistory.com/149

**Comment by develiberta** [comment]
<a href="https://shleeverse.notion.site/42-164a84223a0e466fb6591d08e6f1da69">아이템 42

**Comment by povia** [comment]
[아이템 42])(https://pumped-hell-0a1.notion.site/Item-42-Prefer-lambdas-to-anonymous-classes-f9114cd97441460397ba07ec0660794f)
