### ISSUE TITLE
[아이템 43] 람다보다는 메서드 참조를 사용하라.

### ISSUE THREAD

**Issue by catsbi** [devbook-study/effectivejava#44]
- 아이템 번호 :  43
- 제목 :  람다보다는 메서드 참조를 사용하라.
- 만료일 : 2022-01-23

**Comment by catsbi** [comment]
[아이템 43](https://catsbi.oopy.io/5861b4b5-60fa-4a6e-aadf-5caeafe68b1e#7d080750-9626-4751-bb7c-4377522703d7)

**Comment by csbiy** [comment]
https://devcs96.github.io/2022/01/19/2022-01-19-Item43/#more

**Comment by JoyDaheeCha** [comment]
https://joyful-class-maker.tistory.com/149

**Comment by develiberta** [comment]
<a href="https://shleeverse.notion.site/43-f7a70b1b0f784c46bf900576cf9f6af8">아이템 43

**Comment by povia** [comment]
[아이템 43](https://pumped-hell-0a1.notion.site/Item-43-Prefer-method-references-to-lambdas-ab6f21f38e1742b9a1bb835fb7c63a82)
