### ISSUE TITLE
[아이템 44] 표준 함수형 인터페이스를 사용하라.

### ISSUE THREAD

**Issue by catsbi** [devbook-study/effectivejava#45]
- 아이템 번호 : 44
- 제목 : 표준 함수형 인터페이스를 사용하라.
- 만료일 :2022-01-23

**Comment by catsbi** [comment]
[아이템 44](https://catsbi.oopy.io/5861b4b5-60fa-4a6e-aadf-5caeafe68b1e#1c5758bd-11f4-41a6-8441-51c8b7fc92c5)

**Comment by csbiy** [comment]
https://devcs96.github.io/2022/01/21/2022-01-21-Item44/#more

**Comment by JoyDaheeCha** [comment]
https://joyful-class-maker.tistory.com/149

**Comment by develiberta** [comment]
<a href="https://shleeverse.notion.site/44-cdf7be1cc9b143d2b2ccc564a2bb25e3">아이템 44

**Comment by povia** [comment]
[아이템 44](https://pumped-hell-0a1.notion.site/Item-44-Favor-the-use-of-standard-functional-interfaces-ed4b9dfe2e3841df9636968e7ceecb55)
