### ISSUE TITLE
[아이템 45] 스트림은 주의해서 사용하라.

### ISSUE THREAD

**Issue by catsbi** [devbook-study/effectivejava#46]
- 아이템 번호 :  45
- 제목 : 스트림은 주의해서 사용하라.
- 만료일 : 2022-01-23

**Comment by catsbi** [comment]
[아이템 45](https://catsbi.oopy.io/5861b4b5-60fa-4a6e-aadf-5caeafe68b1e#9107b645-613d-4638-a79e-ef88c358beef)

**Comment by csbiy** [comment]
https://devcs96.github.io/2022/01/22/2022-01-22-Item45/#more

**Comment by JoyDaheeCha** [comment]
https://joyful-class-maker.tistory.com/149

**Comment by develiberta** [comment]
<a href="https://shleeverse.notion.site/45-cc98204b649b43fbad70f589fd500868">아이템 45

**Comment by povia** [comment]
[아이템 45](https://pumped-hell-0a1.notion.site/Item-45-Use-streams-judiciously-15a8ee71f9e44162910395ee8874e6c5)
