### ISSUE TITLE
[아이템 46] 스트림에서는 부작용 없는 함수를 사용하라.

### ISSUE THREAD

**Issue by catsbi** [devbook-study/effectivejava#47]
- 아이템 번호 :  46
- 제목 : 스트림에서는 부작용 없는 함수를 사용하라.
- 만료일 : 2022-01-23

**Comment by catsbi** [comment]
[아이템 46](https://catsbi.oopy.io/5861b4b5-60fa-4a6e-aadf-5caeafe68b1e#21ac9591-c9b8-45e8-a19f-0962a3416c04)

**Comment by develiberta** [comment]
<a href="https://shleeverse.notion.site/46-564081ac0e554402acd03ee836eeccb8">아이템 46

**Comment by JoyDaheeCha** [comment]
https://joyful-class-maker.tistory.com/149

**Comment by povia** [comment]
[아이템 46](https://pumped-hell-0a1.notion.site/Item-46-Prefer-side-effect-free-functions-in-streams-5003ee2228174d9a9b0461e66dcaa4ab)
