### ISSUE TITLE
[아이템 47] 반환 타입으로는 스트림보다 컬렉션이 낫다

### ISSUE THREAD

**Issue by catsbi** [devbook-study/effectivejava#48]
- 아이템 번호 : 47
- 제목 : 반환 타입으로는 스트림보다 컬렉션이 낫다
- 만료일 : 2022-01-30

**Comment by catsbi** [comment]
[아이템 47](https://catsbi.oopy.io/5861b4b5-60fa-4a6e-aadf-5caeafe68b1e#ba54a9d7-04c8-49c3-bf39-a899b7b0fb92)

**Comment by povia** [comment]
[아이템 47](https://pumped-hell-0a1.notion.site/Item-47-Prefer-Collection-to-Stream-as-a-return-type-60490a206ae64df99a1d75d9de0270fa)

**Comment by csbiy** [comment]
https://devcs96.github.io/2022/01/31/2022-01-31-Item47/#more
