### ISSUE TITLE
[아이템 48] 스트림 병렬화는 주의해서 적용하라

### ISSUE THREAD

**Issue by catsbi** [devbook-study/effectivejava#49]
- 아이템 번호 : 48
- 제목 : 스트림 병렬화는 주의해서 적용하라
- 만료일 : 2022-01-30

**Comment by catsbi** [comment]
[아이템 48](https://catsbi.oopy.io/5861b4b5-60fa-4a6e-aadf-5caeafe68b1e#d34e35bc-9a83-414e-88c2-37458a03f3dd)

**Comment by povia** [comment]
[아이템 48](https://pumped-hell-0a1.notion.site/Item-48-Use-caution-when-making-streams-parallel-b4341b0704e3494aaa7ef610255b2346)

**Comment by csbiy** [comment]
https://devcs96.github.io/2022/01/27/2022-01-27-Item48/#more
