### ISSUE TITLE
[아이템 5] 자원을 직접 명시하지 말고 의존 객체 주입을 사용하라

### ISSUE THREAD

**Issue by catsbi** [devbook-study/effectivejava#5]
- 아이템 번호 :  5
- 제목 :  자원을 직접 명시하지 말고 의존 객체 주입을 사용하라
- 만료일 : 2021-12-05

**Comment by catsbi** [comment]
[아이템 5](https://catsbi.oopy.io/d7f3a636-b613-453b-91c7-655d71fda2b1#99fc646f-2f60-43d4-9418-07544af02d43)

**Comment by povia** [comment]
https://povia.tistory.com/80

**Comment by csbiy** [comment]
[item05.zip](https://github.com/devbook-study/effectivejava/files/7655642/item05.zip)
