### ISSUE TITLE
[아이템 49] 매개변수가 유효한지 검사하라

### ISSUE THREAD

**Issue by catsbi** [devbook-study/effectivejava#50]
- 아이템 번호 : 49
- 제목 : 매개변수가 유효한지 검사하라
- 만료일 :2022-01-30

**Comment by catsbi** [comment]
[아이템 49](https://catsbi.oopy.io/1b439cd5-58aa-4cb1-a715-2bfa66afc72a#751b185f-4978-4581-85c9-5bf10d5780c8)

**Comment by povia** [comment]
[아이템 49](https://pumped-hell-0a1.notion.site/Item-49-Check-parameters-for-validity-4fa184b165a64c1bac7f794b50c3f366)

**Comment by tongnamuu** [comment]
https://www.notion.so/Item-49-a4bc9befc8504a5b95f41723bc80a39a

**Comment by csbiy** [comment]
https://devcs96.github.io/2022/01/27/2022-01-27-Item49/#more
