### ISSUE TITLE
[아이템 50] 적시에 방어적 복사본을 만들라

### ISSUE THREAD

**Issue by catsbi** [devbook-study/effectivejava#51]
- 아이템 번호 :  50
- 제목 : 적시에 방어적 복사본을 만들라
- 만료일 :2022-01-30

**Comment by catsbi** [comment]
[아이템 50](https://catsbi.oopy.io/1b439cd5-58aa-4cb1-a715-2bfa66afc72a#0ac16161-568b-4089-bb04-6aa56ff4b586)

**Comment by povia** [comment]
[아이템 50](https://pumped-hell-0a1.notion.site/Item-50-Make-defensive-copies-when-needed-e3b1362d07f04810aedba85d03fc4b2e)

**Comment by csbiy** [comment]
https://devcs96.github.io/2022/01/27/2022-01-27-Item50/#more
