### ISSUE TITLE
[아이템 51] 메서드 시그니처를 신중히 설계하라

### ISSUE THREAD

**Issue by catsbi** [devbook-study/effectivejava#52]
- 아이템 번호 : 51
- 제목 : 메서드 시그니처를 신중히 설계하라
- 만료일 :2022-01-30

**Comment by catsbi** [comment]
[아이템 51](https://catsbi.oopy.io/1b439cd5-58aa-4cb1-a715-2bfa66afc72a#25522a52-7bbc-438b-9486-996214e6a362)

**Comment by povia** [comment]
[아이템 51](https://pumped-hell-0a1.notion.site/Item-51-Design-method-signatures-carefully-9376c040e4bf49e98c428d08bc24c86a)

**Comment by csbiy** [comment]
https://devcs96.github.io/2022/01/27/2022-01-27-Item51/#more
