### ISSUE TITLE
[아이템 52] 다중정의는 신중히 사용하라

### ISSUE THREAD

**Issue by catsbi** [devbook-study/effectivejava#53]
- 아이템 번호 : 52
- 제목 :  다중정의는 신중히 사용하라
- 만료일 : 2022-02-13

**Comment by catsbi** [comment]
[아이템 52](https://catsbi.oopy.io/1b439cd5-58aa-4cb1-a715-2bfa66afc72a#a30be72a-4019-4ade-b62d-4f89ff9dc03e)

**Comment by csbiy** [comment]
https://devcs96.github.io/2022/01/31/2022-01-31-Item52/#more

**Comment by povia** [comment]
[아이템52](https://pumped-hell-0a1.notion.site/Item-52-Use-overloading-judiciously-418673513cc84f98ae1e93384dafa8be)

**Comment by JoyDaheeCha** [comment]
https://joyful-class-maker.tistory.com/155
