### ISSUE TITLE
[아이템 53] 가변인수는 신중히 사용하라

### ISSUE THREAD

**Issue by catsbi** [devbook-study/effectivejava#54]
- 아이템 번호 :  53
- 제목 :  가변인수는 신중히 사용하라
- 만료일 : 2022-02-13

**Comment by catsbi** [comment]
[아이템 53](https://catsbi.oopy.io/1b439cd5-58aa-4cb1-a715-2bfa66afc72a#8abf0007-b7e6-4dd9-be99-3fa4acaaf028)

**Comment by csbiy** [comment]
https://devcs96.github.io/2022/02/03/2022-02-03-Item53/#more

**Comment by povia** [comment]
[아이템53](https://pumped-hell-0a1.notion.site/Item-53-Use-varargs-judiciously-8795f1328586423293494beb64d8a80f)

**Comment by JoyDaheeCha** [comment]
https://joyful-class-maker.tistory.com/155
