### ISSUE TITLE
[아이템 54]  null이 아닌, 빈 컬렉션이나 배열을 반환하라

### ISSUE THREAD

**Issue by catsbi** [devbook-study/effectivejava#55]
- 아이템 번호 : 54
- 제목 :   null이 아닌, 빈 컬렉션이나 배열을 반환하라
- 만료일 : 2022-02-13

**Comment by catsbi** [comment]
[아이템 54](https://catsbi.oopy.io/1b439cd5-58aa-4cb1-a715-2bfa66afc72a#f481408f-726c-4e4d-b0b5-40e746092021)

**Comment by csbiy** [comment]
https://devcs96.github.io/2022/02/05/2022-02-05-Item54/#more

**Comment by povia** [comment]
[아이템54](https://pumped-hell-0a1.notion.site/Item-54-Return-empty-collections-or-arrays-not-nulls-8c4cfef6d43443fd8293688e25aaca89)

**Comment by JoyDaheeCha** [comment]
https://joyful-class-maker.tistory.com/155
