### ISSUE TITLE
[아이템 55] 옵셔널 반환은 신중히 하라

### ISSUE THREAD

**Issue by catsbi** [devbook-study/effectivejava#56]
- 아이템 번호 : 55
- 제목 :  옵셔널 반환은 신중히 하라
- 만료일 : 2022-02-13

**Comment by catsbi** [comment]
[아이템 55](https://catsbi.oopy.io/1b439cd5-58aa-4cb1-a715-2bfa66afc72a#024d194d-a695-4223-b988-48487d121bc5)

**Comment by csbiy** [comment]
https://devcs96.github.io/2022/02/13/2022-02-13-item55/#more

**Comment by povia** [comment]
[아이템55](https://pumped-hell-0a1.notion.site/Item-55-Return-optionals-judiciously-245f8b326cf64bb6a040ad2ace56eb1b)

**Comment by JoyDaheeCha** [comment]
https://joyful-class-maker.tistory.com/155
