### ISSUE TITLE
[아이템 56]  공개된 API 요소에는 항상 문서화 주석을 작성하라

### ISSUE THREAD

**Issue by catsbi** [devbook-study/effectivejava#57]
- 아이템 번호 :  56
- 제목 : 공개된 API 요소에는 항상 문서화 주석을 작성하라
- 만료일 : 2022-02-13

**Comment by catsbi** [comment]
[아이템 56](https://catsbi.oopy.io/1b439cd5-58aa-4cb1-a715-2bfa66afc72a#bb57419c-9dcc-478c-8e54-e067d5bef112)

**Comment by csbiy** [comment]
https://devcs96.github.io/2022/02/13/2022-02-13-item56/#more

**Comment by povia** [comment]
[아이템 56](https://pumped-hell-0a1.notion.site/Item-56-Write-doc-comments-for-all-exposed-API-elements-c439029cd92645c3a27ede63554f6aef)

**Comment by JoyDaheeCha** [comment]
https://joyful-class-maker.tistory.com/155
