### ISSUE TITLE
[아이템 57] 지역변수의 범위를 최소화하라

### ISSUE THREAD

**Issue by catsbi** [devbook-study/effectivejava#58]
- 아이템 번호 : 57
- 제목 : 지역변수의 범위를 최소화하라
- 만료일 : 2022-02-20

**Comment by povia** [comment]
[아이템 57](https://pumped-hell-0a1.notion.site/Item-57-Minimize-the-scope-of-local-variables-11ea250ebf57447098e563335fd4ef14)

**Comment by catsbi** [comment]
[아이템 57](https://catsbi.oopy.io/94095769-531f-4037-b514-12f0c896b9f2#ab0325e2-2fad-4461-ae4a-67fc755e53ce)
