### ISSUE TITLE
[아이템 58] 전통적인 for 문보다는 for-each 문을 사용하라

### ISSUE THREAD

**Issue by catsbi** [devbook-study/effectivejava#59]
- 아이템 번호 : 58
- 제목 : 전통적인 for 문보다는 for-each 문을 사용하라
- 만료일 : 2022-02-20

**Comment by tongnamuu** [comment]
https://www.notion.so/Item-58-for-for-each-3ea96f12d74449b19c10bc3383876cd7

**Comment by povia** [comment]
[아이템 58](https://pumped-hell-0a1.notion.site/Item-58-Prefer-for-each-loops-to-traditional-for-loops-a37e72e1744a4a29a88f0f5b21627f37)

**Comment by catsbi** [comment]
[아이템 58](https://catsbi.oopy.io/94095769-531f-4037-b514-12f0c896b9f2#92705f3f-761e-4412-aac0-60795f1bf5cc)
