### ISSUE TITLE
[아이템 6] 불필요한 객체 생성을 피하라

### ISSUE THREAD

**Issue by catsbi** [devbook-study/effectivejava#6]
- 아이템 번호 : 6
- 제목 :  불필요한 객체 생성을 피하라
- 만료일 : 2021-12-05

**Comment by povia** [comment]
https://povia.tistory.com/81

**Comment by catsbi** [comment]
[아이템 6](https://catsbi.oopy.io/d7f3a636-b613-453b-91c7-655d71fda2b1#1ea9449f-6380-44b2-8bee-90b584d28905)

**Comment by csbiy** [comment]
[item06.zip](https://github.com/devbook-study/effectivejava/files/7655643/item06.zip)

**Comment by tongnamuu** [comment]
https://www.notion.so/Item-6-1ee9ddf9914c4153af326b64f675aaae
