### ISSUE TITLE
[아이템 59] 라이브러리를 익히고 사용하라

### ISSUE THREAD

**Issue by catsbi** [devbook-study/effectivejava#60]
- 아이템 번호 : 59
- 제목 :  라이브러리를 익히고 사용하라
- 만료일 : 2022-02-20

**Comment by povia** [comment]
[아이템 59](https://pumped-hell-0a1.notion.site/Item-59-Know-and-use-the-libraries-ba5abb9690894b1cb434bc9291d55759)

**Comment by catsbi** [comment]
[아이템 59](https://catsbi.oopy.io/94095769-531f-4037-b514-12f0c896b9f2#d9fa4dd2-3269-400f-9f1b-330ba2409de7)
