### ISSUE TITLE
[아이템 60] 정확한 답이 필요하다면 float와 double은 피하라

### ISSUE THREAD

**Issue by catsbi** [devbook-study/effectivejava#61]
- 아이템 번호 : 60
- 제목 : 정확한 답이 필요하다면 float와 double은 피하라
- 만료일 : 2022-02-20

**Comment by povia** [comment]
[아이템 60](https://pumped-hell-0a1.notion.site/Item-60-Avoid-float-and-double-if-exact-answers-are-required-581d26a57e6748658be1ffe5f8de810a)

**Comment by catsbi** [comment]
[아이템 60](https://catsbi.oopy.io/94095769-531f-4037-b514-12f0c896b9f2#f9072e6a-6645-4285-93f1-aad7e13c4288)
