### ISSUE TITLE
[아이템 61] 박싱된 기본 타입보다는 기본 타입을 사용하라

### ISSUE THREAD

**Issue by catsbi** [devbook-study/effectivejava#62]
- 아이템 번호 :  61
- 제목 :  박싱된 기본 타입보다는 기본 타입을 사용하라
- 만료일 : 2022-02-20

**Comment by povia** [comment]
[아이템 61](https://pumped-hell-0a1.notion.site/Item-61-Prefer-primitive-types-to-boxed-primitives-02920d304dc14137904c54ad06237dd1)

**Comment by catsbi** [comment]
[아이템 61](https://catsbi.oopy.io/94095769-531f-4037-b514-12f0c896b9f2#d2f780c0-9782-42f3-8977-bbfe79be58ee)
