### ISSUE TITLE
[아이템 62] 다른 타입이 적절하다면 문자열 사용을 피하라.

### ISSUE THREAD

**Issue by catsbi** [devbook-study/effectivejava#63]
- 아이템 번호 : 62
- 제목 : 다른 타입이 적절하다면 문자열 사용을 피하라.
- 만료일 : 2022-02-27

**Comment by develiberta** [comment]
https://shleeverse.notion.site/62-b1cf1c39bb5842e1bafb73fba2afdf34

**Comment by povia** [comment]
[아이템 62](https://pumped-hell-0a1.notion.site/Item-62-Avoid-strings-where-other-types-are-more-appropriate-913138e547214262a66f77a1bbc09597)

**Comment by catsbi** [comment]
[아이템 62](https://catsbi.oopy.io/94095769-531f-4037-b514-12f0c896b9f2#2d2b671d-9606-45fa-8b15-9c82665c9191)
