### ISSUE TITLE
[아이템 63] 문자열 연결은 느리니 주의하라.

### ISSUE THREAD

**Issue by catsbi** [devbook-study/effectivejava#64]
- 아이템 번호 : 63
- 제목 :  문자열 연결은 느리니 주의하라.
- 만료일 : 2022-02-27

**Comment by develiberta** [comment]
https://shleeverse.notion.site/63-277c578e6352416e82c766975cb93059

**Comment by povia** [comment]
[아이템 63](https://pumped-hell-0a1.notion.site/Item-63-Beware-the-performance-of-string-concatenation-6eba3f0fa0944555b63342fa7aea77c8)

**Comment by catsbi** [comment]
[아이템 63](https://catsbi.oopy.io/94095769-531f-4037-b514-12f0c896b9f2#3336d931-9d11-46c5-b8ec-9e20ad092e7a)
