### ISSUE TITLE
[아이템 64] 객체는 인터페이스를 사용해 참조하라.

### ISSUE THREAD

**Issue by catsbi** [devbook-study/effectivejava#65]
- 아이템 번호 : 64
- 제목 : 객체는 인터페이스를 사용해 참조하라.
- 만료일 : 2022-02-27

**Comment by develiberta** [comment]
https://shleeverse.notion.site/64-c65c71a36a1b4b12a9f22ffc2beb466f

**Comment by catsbi** [comment]
[아이템 64](https://catsbi.oopy.io/94095769-531f-4037-b514-12f0c896b9f2#b4a0afa6-8efa-4c94-b5b5-2b711c0dc2c6)

**Comment by povia** [comment]
[아이템 64](https://pumped-hell-0a1.notion.site/Item-64-Refer-to-objects-by-their-interfaces-56520118f09a49799d62378546714d0a)
