### ISSUE TITLE
[아이템 65] 리플렉션보다는 인터페이스를 사용하라.

### ISSUE THREAD

**Issue by catsbi** [devbook-study/effectivejava#66]
- 아이템 번호 :  65
- 제목 :  리플렉션보다는 인터페이스를 사용하라.
- 만료일 : 2022-02-27

**Comment by develiberta** [comment]
https://shleeverse.notion.site/65-530aa8b559cc469ca4d39bf467024ccf

**Comment by catsbi** [comment]
[아이템 65](https://catsbi.oopy.io/94095769-531f-4037-b514-12f0c896b9f2#38d2e8ac-4ef9-4c40-95fb-00af3c17255a)

**Comment by povia** [comment]
[아이템 65](https://pumped-hell-0a1.notion.site/Item-65-Prefer-interfaces-to-reflection-958b771f912440e4a98978e86780938d)
