### ISSUE TITLE
[아이템 66] 네이티브 메서드는 신중히 사용하라.

### ISSUE THREAD

**Issue by catsbi** [devbook-study/effectivejava#67]
- 아이템 번호 :  66
- 제목 :  네이티브 메서드는 신중히 사용하라.
- 만료일 : 2022-02-27

**Comment by develiberta** [comment]
https://shleeverse.notion.site/66-6a623639a2ae4e318c03af378888a4e3

**Comment by catsbi** [comment]
[아이템 66](https://catsbi.oopy.io/94095769-531f-4037-b514-12f0c896b9f2#d3d379c2-8798-4d15-9a43-63f9c4bca6ad)

**Comment by povia** [comment]
[아이템 66](https://pumped-hell-0a1.notion.site/Item-66-Use-native-methods-judiciously-a9117bd557dd4961a6ac3b30047bb287)
