### ISSUE TITLE
[아이템 67] 최적화는 신중히 하라

### ISSUE THREAD

**Issue by catsbi** [devbook-study/effectivejava#68]
- 아이템 번호 : 67
- 제목 : 최적화는 신중히 하라
- 만료일 : 2022-03-06

**Comment by catsbi** [comment]
[아이템 67](https://catsbi.oopy.io/94095769-531f-4037-b514-12f0c896b9f2#47247cd0-c1cd-4e45-bac7-e077992e007b)

**Comment by povia** [comment]
[아이템 67](https://pumped-hell-0a1.notion.site/Item-67-Optimize-judiciously-a5dbaf48d51548688b6cb6adad8a5b5e)

**Comment by csbiy** [comment]
https://devcs96.github.io/2022/03/06/Item67/#more

**Comment by JoyDaheeCha** [comment]
https://joyful-class-maker.tistory.com/159
