### ISSUE TITLE
[아이템 68] 일반적으로 통용되는 명명 규칙을 따르라

### ISSUE THREAD

**Issue by catsbi** [devbook-study/effectivejava#69]
- 아이템 번호 :  68
- 제목 : 일반적으로 통용되는 명명 규칙을 따르라
- 만료일 : 2022-03-06

**Comment by catsbi** [comment]
[아이템 68](https://catsbi.oopy.io/94095769-531f-4037-b514-12f0c896b9f2#2430cf21-56e6-41a3-8a9d-d957c7bdb631)

**Comment by povia** [comment]
[아이템 68](https://pumped-hell-0a1.notion.site/Item-68-Adhere-to-generally-accepted-naming-conventions-a4c736467d4546359b79dddfa0028c8f)

**Comment by csbiy** [comment]
https://devcs96.github.io/2022/03/06/Item68/#more

**Comment by JoyDaheeCha** [comment]
https://joyful-class-maker.tistory.com/159
