### ISSUE TITLE
[아이템 7] 다 쓴 객체 참조를 해제하라

### ISSUE THREAD

**Issue by catsbi** [devbook-study/effectivejava#7]
- 아이템 번호 :  7
- 제목 :  다 쓴 객체 참조를 해제하라
- 만료일 : 2021-12-05

**Comment by catsbi** [comment]
[아이템 7](https://catsbi.oopy.io/d7f3a636-b613-453b-91c7-655d71fda2b1#a9181e25-bc84-413f-a814-084535284933)

**Comment by csbiy** [comment]
[item07.zip](https://github.com/devbook-study/effectivejava/files/7655645/item07.zip)

**Comment by tongnamuu** [comment]
https://www.notion.so/Item-7-87efffdca28a4928bd29bae678a70163
