### ISSUE TITLE
[아이템 69] 예외는 진짜 예외 상황에만 사용하라

### ISSUE THREAD

**Issue by catsbi** [devbook-study/effectivejava#70]
- 아이템 번호 : 69
- 제목 : 예외는 진짜 예외 상황에만 사용하라
- 만료일 : 2022-03-06

**Comment by catsbi** [comment]
[아이템 69](https://catsbi.oopy.io/a18e12e1-19f9-46cf-8168-f8d5dc41c223#9a43967e-ce34-4556-af9e-095451637e7d)

**Comment by povia** [comment]
[아이템 69](https://pumped-hell-0a1.notion.site/Item-69-Use-exceptions-only-for-exceptional-conditions-48f641fe44b540f4b749fb42cbd9f58a)

**Comment by csbiy** [comment]
https://devcs96.github.io/2022/03/06/Item69/#more

**Comment by JoyDaheeCha** [comment]
https://joyful-class-maker.tistory.com/159
