### ISSUE TITLE
[아이템 70] 복구할 수 있는 상황에는 검사 예외를, 프로그래밍 오류에는 런타임 예외를 사용하라

### ISSUE THREAD

**Issue by catsbi** [devbook-study/effectivejava#71]
- 아이템 번호 :  70
- 제목 : 복구할 수 있는 상황에는 검사 예외를, 프로그래밍 오류에는 런타임 예외를 사용하라
- 만료일 : 2022-03-06

**Comment by catsbi** [comment]
[아이템 70](https://catsbi.oopy.io/a18e12e1-19f9-46cf-8168-f8d5dc41c223#6227fe2a-f9b2-4d85-8f45-2bcc79ff2c58)

**Comment by povia** [comment]
[아이템 70](https://pumped-hell-0a1.notion.site/Item-70-Use-checked-exceptions-for-recoverable-conditions-and-runtime-exceptions-for-programming-er-2dd8465131364f2988ba784ea97b1c80)

**Comment by csbiy** [comment]
https://devcs96.github.io/2022/03/06/Item70/#more

**Comment by JoyDaheeCha** [comment]
https://joyful-class-maker.tistory.com/159
