### ISSUE TITLE
[아이템 71]  필요 없는 검사 예외 사용은 피하라

### ISSUE THREAD

**Issue by catsbi** [devbook-study/effectivejava#72]
- 아이템 번호 : 71
- 제목 :   필요 없는 검사 예외 사용은 피하라
- 만료일 : 2022-03-06

**Comment by catsbi** [comment]
[아이템 71](https://catsbi.oopy.io/a18e12e1-19f9-46cf-8168-f8d5dc41c223#3508f7d1-f07b-4b56-b5bc-a5e593830e05)

**Comment by povia** [comment]
[아이템 71](https://pumped-hell-0a1.notion.site/Item-71-Avoid-unnecessary-use-of-checked-exceptions-886d431611ff40e79b4a67cbf7839fa7)

**Comment by tongnamuu** [comment]
https://www.notion.so/Item-71-67a9c3baa7f644449ebd1668baa4c7aa

**Comment by csbiy** [comment]
https://devcs96.github.io/2022/03/06/Item71/#more
