### ISSUE TITLE
[아이템 72] 표준 예외를 사용하라.

### ISSUE THREAD

**Issue by catsbi** [devbook-study/effectivejava#73]
- 아이템 번호 :  72
- 제목 :  표준 예외를 사용하라.
- 만료일 : 2022-03-13

**Comment by catsbi** [comment]
[아이템 72](https://catsbi.oopy.io/a18e12e1-19f9-46cf-8168-f8d5dc41c223#37654104-ab22-4bd4-a887-0331df8655f1)

**Comment by csbiy** [comment]
https://devcs96.github.io/2022/03/13/Item72/#more

**Comment by povia** [comment]
[아이템 72](https://pumped-hell-0a1.notion.site/Item-72-Favor-the-use-of-standard-exceptions-8a50ceabbfba4df8b4015ab1bd936e0e)

**Comment by tongnamuu** [comment]
https://www.notion.so/Item-72-3babff35b28544ff907af74be90db076
