### ISSUE TITLE
[아이템 73] 추상화 수준에 맞는 예외를 던져라.

### ISSUE THREAD

**Issue by catsbi** [devbook-study/effectivejava#74]
- 아이템 번호 :  73
- 제목 : 추상화 수준에 맞는 예외를 던져라.
- 만료일 : 2022-03-13

**Comment by catsbi** [comment]
[아이템 73](https://catsbi.oopy.io/a18e12e1-19f9-46cf-8168-f8d5dc41c223#0a6a046b-fe3e-46be-8490-0f90237e3aa0)

**Comment by csbiy** [comment]
https://devcs96.github.io/2022/03/13/Item73/#more

**Comment by povia** [comment]
[아이템 73](https://pumped-hell-0a1.notion.site/Item-73-Throw-exceptions-appropriate-to-the-abstraction-c998b74b8af54c87974960e2a4db1172)

**Comment by tongnamuu** [comment]
https://www.notion.so/Item-73-d3b1635a767a4d78979fb51e0fb6f747
