### ISSUE TITLE
[아이템 74] 메서드가 던지는 모든 예외를 문서화하라.

### ISSUE THREAD

**Issue by catsbi** [devbook-study/effectivejava#75]
- 아이템 번호 :  74
- 제목 : 메서드가 던지는 모든 예외를 문서화하라.
- 만료일 : 2022-03-13

**Comment by catsbi** [comment]
[아이템 74](https://catsbi.oopy.io/a18e12e1-19f9-46cf-8168-f8d5dc41c223#c4b6ea98-0899-40ba-8d3a-ece041b3261a)

**Comment by csbiy** [comment]
https://devcs96.github.io/2022/03/13/Item74/#more

**Comment by povia** [comment]
[아이템 74](https://pumped-hell-0a1.notion.site/Item-74-Document-all-exceptions-thrown-by-each-method-756d9db956ec43a99c54013d13ee0a00)

**Comment by tongnamuu** [comment]
https://www.notion.so/Item-74-71d26106b59a450ea67bc73edb3e5b70
