### ISSUE TITLE
[아이템 75] 예외의 상세 메세지에 실패 관련 정보를 담으라.

### ISSUE THREAD

**Issue by catsbi** [devbook-study/effectivejava#76]
- 아이템 번호 :  75
- 제목 : 예외의 상세 메세지에 실패 관련 정보를 담으라.
- 만료일 : 2022-03-13

**Comment by catsbi** [comment]
[아이템 75](https://catsbi.oopy.io/a18e12e1-19f9-46cf-8168-f8d5dc41c223#265e7370-a131-4f5f-85f7-2f132c6fbe28)

**Comment by csbiy** [comment]
https://devcs96.github.io/2022/03/13/Item75/#more

**Comment by povia** [comment]
[아이템 75](https://pumped-hell-0a1.notion.site/Item-75-Include-failure-capture-information-in-detail-messages-4de1e54ef04f416c877f8c113477796b)

**Comment by tongnamuu** [comment]
https://www.notion.so/Item-75-545e102f53174b0b951bad7692bdfd58
