### ISSUE TITLE
[아이템 76] 가능한 한 실패 원자적으로 만들라.

### ISSUE THREAD

**Issue by catsbi** [devbook-study/effectivejava#77]
- 아이템 번호 :  76
- 제목 :  가능한 한 실패 원자적으로 만들라.
- 만료일 : 2022-03-13

**Comment by catsbi** [comment]
[아이템 76](https://catsbi.oopy.io/a18e12e1-19f9-46cf-8168-f8d5dc41c223#4aa72c1c-feec-4f6d-b198-0d57b1e56541)

**Comment by csbiy** [comment]
https://devcs96.github.io/2022/03/13/Item76/#more

**Comment by povia** [comment]
[아이템 76](https://pumped-hell-0a1.notion.site/Item-76-Strive-for-failure-atomicity-8b6897cc8b62479eb405b363d1e6bfcd)
