### ISSUE TITLE
[아이템 77] 예외를 무시하지 말라

### ISSUE THREAD

**Issue by catsbi** [devbook-study/effectivejava#78]
- 아이템 번호 : 77
- 제목 : 예외를 무시하지 말라
- 만료일 : 2022-03-20

**Comment by povia** [comment]
[아이템 77](https://pumped-hell-0a1.notion.site/Item-77-Don-t-ignore-exceptions-6dd7244d68dd4d32a790c1b0e96854ed)

**Comment by JoyDaheeCha** [comment]
https://joyful-class-maker.tistory.com/160

**Comment by catsbi** [comment]
[아이템 77](https://catsbi.oopy.io/a18e12e1-19f9-46cf-8168-f8d5dc41c223#adea5378-e582-4c1e-aa35-f5e20fc6ebdc)

**Comment by csbiy** [comment]
https://devcs96.github.io/2022/03/20/Item77/#more

**Comment by tongnamuu** [comment]
https://www.notion.so/Item-77-9e68c49ed12d4fc7b92c0c3a0faa03b2
