### ISSUE TITLE
[아이템 78] 공유 중인 가변 데이터는 동기화해 사용하라

### ISSUE THREAD

**Issue by catsbi** [devbook-study/effectivejava#79]
- 아이템 번호 : 78
- 제목 : 공유 중인 가변 데이터는 동기화해 사용하라
- 만료일 : 2022-03-20

**Comment by povia** [comment]
[아이템 78](https://pumped-hell-0a1.notion.site/Item-78-Synchronize-access-to-shared-mutable-data-3e89bf282a6c425998a1d5379207bb1f)

**Comment by JoyDaheeCha** [comment]
https://joyful-class-maker.tistory.com/160

**Comment by catsbi** [comment]
[아이템 78](https://catsbi.oopy.io/a30cbbc8-3788-44e2-847d-f9adf9800480#794637eb-a6f7-40c6-abad-1a639b9c4c6d)
