### ISSUE TITLE
[아이템 8] finalizer와 cleaner 사용을 피하라

### ISSUE THREAD

**Issue by catsbi** [devbook-study/effectivejava#8]
- 아이템 번호 : 8
- 제목 : finalizer와 cleaner 사용을 피하라
- 만료일 : 2021-12-05

**Comment by catsbi** [comment]
[아이템 8](https://catsbi.oopy.io/d7f3a636-b613-453b-91c7-655d71fda2b1#7d40f098-e1d9-4ad4-a7e1-0c550a601dc3)

**Comment by povia** [comment]
https://povia.tistory.com/83

**Comment by devcs96** [comment]
C:\Users\katd6\OneDrive\바탕 화면\hexo-git-blog\hexoblog\source\_posts\2021-12-05-item8.md

**Comment by csbiy** [comment]
[2021-12-05-item8.md](https://github.com/devbook-study/effectivejava/files/7660124/2021-12-05-item8.md)
