### ISSUE TITLE
[아이템 79] 과도한 동기화는 피하라

### ISSUE THREAD

**Issue by catsbi** [devbook-study/effectivejava#80]
- 아이템 번호 : 79
- 제목 :  과도한 동기화는 피하라
- 만료일 : 2022-03-20

**Comment by povia** [comment]
[아이템 79](https://pumped-hell-0a1.notion.site/Item-79-Avoid-excessive-synchronization-7ba26fa00a5d41fc93ecc82a22048388)

**Comment by JoyDaheeCha** [comment]
https://joyful-class-maker.tistory.com/160

**Comment by catsbi** [comment]
[아이템 79](https://catsbi.oopy.io/a30cbbc8-3788-44e2-847d-f9adf9800480#18c71353-3b68-4f33-85e5-bef6d9e93a81)
