### ISSUE TITLE
[아이템 80] 스레드보다는 실행자, 태스크, 스트림을 애용하라

### ISSUE THREAD

**Issue by catsbi** [devbook-study/effectivejava#81]
- 아이템 번호 : 80
- 제목 : 스레드보다는 실행자, 태스크, 스트림을 애용하라
- 만료일 : 2022-03-20

**Comment by povia** [comment]
[아이템 80](https://pumped-hell-0a1.notion.site/Item-80-Prefer-executors-tasks-and-streams-to-threads-23b92e45b06945a8b5e13658b12473fa)

**Comment by JoyDaheeCha** [comment]
https://joyful-class-maker.tistory.com/160
