### ISSUE TITLE
[아이템 81] wait와 notify보다는 동시성 유틸리티를 애용하라

### ISSUE THREAD

**Issue by catsbi** [devbook-study/effectivejava#82]
- 아이템 번호 : 81
- 제목 :  wait와 notify보다는 동시성 유틸리티를 애용하라
- 만료일 : 2022-03-20

**Comment by povia** [comment]
[아이템 81](https://pumped-hell-0a1.notion.site/Item-81-Prefer-concurrency-utilities-to-wait-and-notify-7e1ce44a2fcf4b1abfa1f817bf52b90e)

**Comment by JoyDaheeCha** [comment]
https://joyful-class-maker.tistory.com/160

**Comment by catsbi** [comment]
[아이템 81](https://catsbi.oopy.io/a30cbbc8-3788-44e2-847d-f9adf9800480#c769c50d-e848-4c7d-84b6-81e5acaaec0b)

**Comment by csbiy** [comment]
https://devcs96.github.io/2022/03/27/Item81/#more
