### ISSUE TITLE
[아이템 82]  스레드 안전성 수준을 문서화하라.

### ISSUE THREAD

**Issue by catsbi** [devbook-study/effectivejava#83]
- 아이템 번호 :  82
- 제목 :  스레드 안전성 수준을 문서화하라.
- 만료일 : 2022-03-27

**Comment by catsbi** [comment]
[아이템 82](https://catsbi.oopy.io/a30cbbc8-3788-44e2-847d-f9adf9800480#76bd69ab-dc39-4fdb-b16f-6fa56f031c4e)

**Comment by povia** [comment]
[아이템 82](https://pumped-hell-0a1.notion.site/Item-82-Document-thread-safety-e2f1b22a394b4a189faf12a8482c446f)

**Comment by csbiy** [comment]
https://devcs96.github.io/2022/03/30/Item82/#more
