### ISSUE TITLE
[아이템 83] 지연 초기화는 신중히 사용하라.

### ISSUE THREAD

**Issue by catsbi** [devbook-study/effectivejava#84]
- 아이템 번호 :  83
- 제목 :  지연 초기화는 신중히 사용하라.
- 만료일 : 2022-03-27

**Comment by catsbi** [comment]
[아이템 83](https://catsbi.oopy.io/a30cbbc8-3788-44e2-847d-f9adf9800480#dfd8f6b6-8a3d-4994-afbd-c21b3acc3734)

**Comment by povia** [comment]
[아이템 83](https://pumped-hell-0a1.notion.site/Item-83-Use-lazy-initialization-judiciously-5330ff45f8d54bebbf9ee7f77eafe2e9)

**Comment by csbiy** [comment]
https://devcs96.github.io/2022/03/30/Item83/#more
