### ISSUE TITLE
[아이템 84] 프로그램의 동작을 스레드 스케줄러에 기대지 말라.

### ISSUE THREAD

**Issue by catsbi** [devbook-study/effectivejava#85]
- 아이템 번호 : 84
- 제목 : 프로그램의 동작을 스레드 스케줄러에 기대지 말라.
- 만료일 : 2022-03-27

**Comment by catsbi** [comment]
[아이템 84](https://catsbi.oopy.io/a30cbbc8-3788-44e2-847d-f9adf9800480#54c45b62-38c7-4e19-b355-b094dfceca02)

**Comment by povia** [comment]
[아이템 84](https://pumped-hell-0a1.notion.site/Item-84-Don-t-depend-on-the-thread-scheduler-1b5470e782064185b6c94f77ffdf502c)

**Comment by csbiy** [comment]
https://devcs96.github.io/2022/04/01/Item84/#more
