### ISSUE TITLE
[아이템 85] 자바 직렬화의 대안을 찾으라. 

### ISSUE THREAD

**Issue by catsbi** [devbook-study/effectivejava#86]
- 아이템 번호 :  85
- 제목 :  자바 직렬화의 대안을 찾으라. 
- 만료일 : 2022-03-27

**Comment by catsbi** [comment]
[아이템 85](https://catsbi.oopy.io/a45ea6f0-c9e7-4426-8782-4aa24d4d3b06#035a9d27-4a0b-4181-b965-e004e8c85f31)

**Comment by povia** [comment]
[아이템 85](https://pumped-hell-0a1.notion.site/Item-85-Prefer-alternatives-to-Java-serialization-959a6fbf74ce43ffaed51b859e8b2796)

**Comment by csbiy** [comment]
https://devcs96.github.io/2022/04/01/Item85/#more
