### ISSUE TITLE
[아이템 86] Serializable을 구현할지는 신중히 결정하라. 

### ISSUE THREAD

**Issue by catsbi** [devbook-study/effectivejava#87]
- 아이템 번호 :  86
- 제목 :  Serializable을 구현할지는 신중히 결정하라. 
- 만료일 : 2022-03-27

**Comment by catsbi** [comment]
[아이템 86](https://catsbi.oopy.io/a45ea6f0-c9e7-4426-8782-4aa24d4d3b06#f829a8eb-3107-4349-a256-3065434a9b47)

**Comment by povia** [comment]
[아이템 86](https://pumped-hell-0a1.notion.site/Item-86-Implement-Serializable-with-great-caution-09903ea5e57d4c58801e4122cc9dc78e)

**Comment by csbiy** [comment]
https://devcs96.github.io/2022/04/03/Item86/#more
