### ISSUE TITLE
[아이템 87] 커스텀 직렬화 형태를 고려해보라.

### ISSUE THREAD

**Issue by catsbi** [devbook-study/effectivejava#88]
- 아이템 번호 :  87
- 제목 : 커스텀 직렬화 형태를 고려해보라.
- 만료일 : 2022-04-03

**Comment by catsbi** [comment]
[아이템 87](https://catsbi.oopy.io/a45ea6f0-c9e7-4426-8782-4aa24d4d3b06#943668e7-aaf1-4274-aadd-6a0e3529c1b7)

**Comment by povia** [comment]
[아이템 87](https://pumped-hell-0a1.notion.site/Item-87-Consider-using-a-custom-serialized-form-ec6728c19e2c421e92d535d1a9f5533c)
