### ISSUE TITLE
[아이템 88] readObject 메서드는 방어적으로 작성하라.

### ISSUE THREAD

**Issue by catsbi** [devbook-study/effectivejava#89]
- 아이템 번호 : 88
- 제목 : readObject 메서드는 방어적으로 작성하라.
- 만료일 : 2022-04-03

**Comment by catsbi** [comment]
[아이템 88](https://catsbi.oopy.io/a45ea6f0-c9e7-4426-8782-4aa24d4d3b06#d7a3f6af-19e2-4239-b51e-52b626a8f707)

**Comment by povia** [comment]
[아이템 88](https://pumped-hell-0a1.notion.site/Item-88-Write-readObject-methods-defensively-0deba74a3ba9494082e1e814283447b1)
