### ISSUE TITLE
[아이템 9] try-finally보다는 try-with-resources를 사용하라

### ISSUE THREAD

**Issue by catsbi** [devbook-study/effectivejava#9]
- 아이템 번호 : 9
- 제목 :  try-finally보다는 try-with-resources를 사용하라
- 만료일 : 2021-12-05

**Comment by povia** [comment]
https://povia.tistory.com/84

**Comment by catsbi** [comment]
[아이템 9](https://catsbi.oopy.io/d7f3a636-b613-453b-91c7-655d71fda2b1#d6df7a30-2bf5-4fa7-b061-8b08fee2beaa)

**Comment by csbiy** [comment]
[2021-12-06-item9.md](https://github.com/devbook-study/effectivejava/files/7660417/2021-12-06-item9.md)
