### ISSUE TITLE
[아이템 89] 인스턴스 수를 통제해야 한다면 readResolve 보단 열거타입을 사용하라. 

### ISSUE THREAD

**Issue by catsbi** [devbook-study/effectivejava#90]
- 아이템 번호 :  89
- 제목 :  인스턴스 수를 통제해야 한다면 readResolve 보단 열거타입을 사용하라. 
- 만료일 : 2022-04-03

**Comment by catsbi** [comment]
[아이템 89](https://catsbi.oopy.io/a45ea6f0-c9e7-4426-8782-4aa24d4d3b06#7617a6cb-8a2d-4dec-ab04-af9ad18ded87)

**Comment by povia** [comment]
[아이템 89](https://pumped-hell-0a1.notion.site/Item-89-For-instance-control-prefer-enum-types-to-readResolve-04f5ff51415c43cb96aac9850d2ba3c0)
