### ISSUE TITLE
[아이템 90] 직렬화된 인스턴스 대신 직렬화 프록시 사용을 검토하라.

### ISSUE THREAD

**Issue by catsbi** [devbook-study/effectivejava#91]
- 아이템 번호 : 90
- 제목 : 직렬화된 인스턴스 대신 직렬화 프록시 사용을 검토하라.
- 만료일 : 2022-04-03

**Comment by catsbi** [comment]
[아이템 90](https://catsbi.oopy.io/a45ea6f0-c9e7-4426-8782-4aa24d4d3b06#95eb64da-6154-4c53-8585-ccec067c332f)

**Comment by povia** [comment]
[아이템 90](https://pumped-hell-0a1.notion.site/Item-90-Consider-serialization-proxies-instead-of-serialized-instances-9128fedd9f11428a94760b48381c3a2a)
